name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Build and check
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Tests
        run: go test -cover ./...

      - name: Force Failure
        run: (exit 0)

      - name: Checkout Source
        uses: actions/checkout@v2

      - name: gosec
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Style
        run: test -z $(go fmt ./...) && echo $?

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
      - name: Build
        run: go build ./main.go

